
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "dangoMM", email = "ocean.in.the.valley@gmail.com"},
]
dependencies = [
    "torch>=2.1.1",
    "torchvision>=0.16.1",
    "ipykernel>=6.27.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
